### ISSUE TITLE
DefaultSort does not work

### ISSUE THREAD

**Issue by JohnyRicio** [contributte/datagrid#601] opened 2018-01-04 09:21 UTC
Hi,

when I use setDefaultSort on init grid, all is ok. But when I set order by column and after reset this, default sort is ignored and data is ordered as was returned from database. I use for datasource kdyby/Dotrine.

Thank you for fix

**Comment by paveljanda** [comment] 2018-01-09 23:03
It should be fixed by now (https://github.com/ublaboo/datagrid/pull/545)

**Comment by JohnyRicio** [comment] 2018-01-10 09:44
Fix is not working. Data are always sorted ASC, but I have $grid->setDefaultSort(['id' => 'DESC']);

**Comment by paveljanda** [comment] 2018-01-10 10:17
@JohnyRicio What version did you try? It is not released yet (just sitting in branch `v5.x`).

**Comment by JohnyRicio** [comment] 2018-01-11 09:09
Current version what I have is 5.4.13. Yesterday, I updated to this version and I did not check if this fix was be released. Maybe It been fixed. Sorry

**Comment by paveljanda** [comment] 2018-01-11 09:13
@JohnyRicio I wrote that is has not been released yet (it will be in following days). But you can test the `v5.x` branch (`HEAD`).

**Comment by JohnyRicio** [comment] 2018-01-11 09:39
@paveljanda Currently I have v5.x-dev 80e5b81 and still not working. Default shorted data is ordered ASC, but I seted it to DESC.

**Comment by paveljanda** [comment] 2018-01-11 09:44
@JohnyRicio I can't find a commit `80e5b81`. :D Where did you got it?

Can you please create a sandbox-like project with some basic functionality that will show that issue and upload it to github / here with zip? Thanks a lot!

**Comment by ne0-cz** [comment] 2018-01-30 14:02
I can confirm this issue for 5.5.5.

```
$grid->setPrimaryKey('post_id');
$grid->setDataSource($this->postFacade->getFluent());
$grid->setDefaultSort(['date' => 'DESC']);

$grid->addColumnDateTime('date', 'Date')
            ->setFitContent()
            ->setSortable();
```

5.4.13 acts as expected:
On load: `ORDER BY date DESC`
Click: `ORDER BY post_id`
Click: `ORDER BY date ASC`
Click: `ORDER BY date DESC`
Click: `ORDER BY post_id`
Click: `ORDER BY date ASC`
Click: `ORDER BY date DESC`
[...]

5.5.5 is wrong:
On load: `ORDER BY date DESC`
Click: `ORDER BY date ASC`
Click: `ORDER BY post_id`
Click: `ORDER BY date ASC`
Click: `ORDER BY post_id`
[...]

Tested with 5.5.1 the issue is there as well (I could not easily try 5.5.0 so I didn't).

**Comment by matoni555** [comment] 2018-02-17 16:09
I have same problem in version 5.5.6.

Set up of sorting:
```
$grid->setDefaultSort([
	'order' => 'DESC',
]);
```
Order column in grid:
![kategorie administrace](https://user-images.githubusercontent.com/3002995/36342890-274e2094-1405-11e8-88e2-cf8d74899cdf.png)

**Comment by paveljanda** [comment] 2018-02-19 08:11
Can you send a PR? :)

**Comment by jaroslavlibal** [comment] 2018-02-26 12:25
Just some observations, not sure if useful:
- The issue occurs also in the current `dev-bootstrap-4` branch.
- When used with the `->setRemeberState(false)` option, then the grid default sort is correctly applied after reseting the sort settings to default (by clicking on the sort button).
- It does not work (means the grid default sort is not applied) when reseting filters with the "reset filters" button.

**Comment by spernica** [comment] 2018-05-23 08:52
Default sorting isn't working. Nette Database, Nette 2.4, datagrid 5.6.0, PHP 7.2.2

$grid->setDefaultSort(['id' => 'DESC']);
1
2
5

If I add column id to grid, then I can filter only with ASC option.

**Comment by attreid** [comment] 2018-06-05 07:01
Maybe help rewrite method getSortNext in class Ublaboo\DataGrid\Column from
```php
public function getSortNext()
{
	$defaultSort = $this->grid->getColumnDefaultSort($this->key);

	if ($this->sort == 'ASC') {
		return [$this->key => $defaultSort === 'DESC' ? FALSE : 'DESC'];
	} else if ($this->sort == 'DESC') {
		return [$this->key => $defaultSort === 'DESC' ? 'ASC' : FALSE];
	}

	return [$this->key => 'ASC'];
}
```
to
```php
public function getSortNext()
{
	if ($this->sort == 'ASC') {
		return [$this->key => 'DESC'];
	} else if ($this->sort == 'DESC') {
		return [$this->key => FALSE];
	}

	return [$this->key => 'ASC'];
}
```

**Comment by matoni555** [comment] 2018-06-15 05:53
Problem is really when remember state is turned on (which is by default).
It works when set `->setRemeberState(false)`

@paveljanda I tried to find out the problem in source, but I did not find any solution. Can you please look at it?

Thanks

**Closed** 2018-07-10 08:34 UTC
Labels: bug-not-confirmed-yet
